Vagrant.configure(2) do |config|
    config.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 4
    end

    config.vm.define "co7" do |co7|
        co7.vm.box = "bento/centos-7.1"

        co7.vm.provider :virtualbox do |vb|
            vb.name = "pgaudit-test-centos-7"
        end

        # Provision the VM
        co7.vm.provision "shell", inline: <<-SHELL
            yum -y install perl
            wget http://dl.fedoraproject.org/pub/epel/7/x86_64/p/perl-IPC-System-Simple-1.25-1.el7.noarch.rpm
            yum -y localinstall perl-IPC-System-Simple-1.25-1.el7.noarch.rpm

            yum -y install git
            yum -y install gcc
            yum -y install readline-devel
            yum -y install zlib-devel
            yum -y install bison
            yum -y install flex
            yum -y install perl-DBD-Pg
            sudo -u vagrant git clone https://github.com/postgres/postgres.git -b REL9_5_STABLE postgres

            cd postgres
            sudo -u vagrant ./configure
            sudo -u vagrant make -j 4 -s install
            make -s install

            cd contrib
            sudo -u vagrant git clone https://github.com/pgaudit/pgaudit.git pgaudit

            cd pgaudit
            sudo -u vagrant make -s check
            make -s install

            echo 'PATH=/usr/local/pgsql/bin:$PATH' >> /etc/profile
            echo 'export PATH' >> /etc/profile
        SHELL
    end

    config.vm.define "u14" do |u14|
        u14.vm.box = "boxcutter/ubuntu1404"

        u14.vm.provider :virtualbox do |vb|
            vb.name = "pgaudit-test-ubuntu-14.04"
        end

        # Provision the VM
        u14.vm.provision "shell", inline: <<-SHELL
            apt-get update

            # Install required Perl modules
            # apt-get install libdbi-perl libdbd-pg-perl

            # Install Perl modules required for building the docs
            apt-get install -y libxml-checker-perl libxml-writer-perl ghostscript

            # Install texlive
            mkdir /root/texlive
            wget -q -O - http://mirror.hmc.edu/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz | tar zxv -C /root//texlive --strip-components=1
            echo "collection-basic 1" >> /root/texlive/texlive.profile
            echo "collection-latex 1" >> /root/texlive/texlive.profile
            /root/texlive/install-tl -profile=/root/texlive/texlive.profile

            echo 'PATH=/usr/local/texlive/2015/bin/x86_64-linux:$PATH' >> /etc/profile
            echo 'export PATH' >> /etc/profile

            /usr/local/texlive/2015/bin/x86_64-linux/tlmgr install caption xcolor listings parskip helvetic ltablex titlesec epstopdf courier
        SHELL
    end

    # Don't share the default vagrant folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Mount pgaudit path for testing
    config.vm.synced_folder "../..", "/pgaudit"

    # Mount backrest for docs
    config.vm.synced_folder "../../../../../../../../../Code/backrest", "/backrest"
end
